### ISSUE TITLE
Nushell 0.97.1 error

### ISSUE THREAD

**Issue by dougg0k** [tesujimath/nu_plugin_bash_env#25]
Hey,

So, today I upgraded nushell to latest version and an error appeared from this plugin, then a simple protocol version increase was enough to fix it.

What I didnt understood was, why have that protocol version in the first place? 

It's like asking, you have to upgrade the plugin everytime there is a new nushell version.

**Comment by tesujimath** [comment]
Yes, that's how the Nu plugin system works.  It's not something that can be mitigated by plugin authors.  We just have to keep tweaking and rebuilding our plugins.  I imagine it will be like this until Nu 1.0 release, and then we'll have stability.

The plugin protocol went through quite a bit of change during 0.90 - 0.94, but has since settled down, so it's generally now a matter of bumping the version number.

I'll do that shortly.

**Comment by dougg0k** [comment]
No, I mean.

`PROTOCOL_VERSION=$(nu --version)`

**Comment by tesujimath** [comment]
Ah, that's an interesting idea.

The benefit is that the plugin continues to work across Nu version updates.

The drawback is that it bypasses the Nu protocol version compatibility check, so unexpected breakage may occur.

But I'm up for this, so let's see how well it works.

**Comment by dougg0k** [comment]
Still, it would require the update if there were a breaking change. 

And in both situations it would break, if new version and if breaking change. Making it redundant.


Cool.

**Comment by tesujimath** [comment]
I'll close this when I've released 0.13 with your version idea.

**Comment by tesujimath** [comment]
Aargh!  This isn't going to work @dougg0k .  The plugin *is* actually broken because the protocol changed.

Nice idea, but for now I'm going to continue releasing a new version for each Nu release.

**Comment by dougg0k** [comment]
Line 337, 382 and 387 change to `.Value[0].String`

Line 157 change to `echo -n "\"Value\":[{\"Record\":{\"val\":{"`
Line 178 change to `echo '},"span":{"start":0,"end":0}}},null]}}]}'`

And fixed.

But now there is a signal msg that needs handling and I dont know how to. At least the plugin works.

```
nu ✗ ssh-agent | bash-env
Agent pid 3508019
╭───────────────┬─────────────────────────────────────╮
│ SSH_AUTH_SOCK │ /tmp/ssh-XXXXXX5U2pmh/agent.3508015 │
│ SSH_AGENT_PID │ 3508019                             │
╰───────────────┴─────────────────────────────────────╯
unexpected input: {"Signal":"Reset"}
```

**Comment by tesujimath** [comment]
I have concluded that implementing the Nu plugin protocol by hand has become unreasonable.  It grew in complexity, and the initial idea of using `jq` to process the protocol is no longer fit for purpose.

I am in the process of adding a Rust layer to interface with the Nu protocol engine, and hand off the actual environment processing to a separate `bash` process.

I'll leave this issue open until that is done, and I have something that works with this new approach.

**Comment by tesujimath** [comment]
My dev branch has a basically working implementation of the Rust protocol wrapper.

I'm pretty happy that this will make it easier to maintain in future.

I need to test it a bit more thoroughly and build the package in CI/CD for the tests.  Not today though.

**Comment by dougg0k** [comment]
I suppose now you can also automate to upload to crates.io, making it easier to update.

https://github.com/marketplace/actions/publish-crates

**Comment by tesujimath** [comment]
I might not automate the crate publishing for now. :smile: 

Thanks for your input here.

**Comment by dougg0k** [comment]
Another thing, maybe you could make the code rust only and even better.

https://github.com/rust-shell-script/rust_cmd_lib

**Comment by tesujimath** [comment]
No, that's not going to work well.

Bash is complex, and trying to emulate it via a third party implementation is going to be an exercise in frustration.

Only by using actual Bash do you get complete compatibility.  Which is what this plugin is all about. :sunglasses:

**Comment by dougg0k** [comment]
It doesnt seem to be emulating anything, but rather running bash through rust.

But, if you say so.

**Comment by tesujimath** [comment]
Ah, so it's a convenience library over `subprocess`, or equivalent.  But that isn't all that inconvenient TBH.

I'm not sure I'm sufficiently interested to spend time looking into it.
