### ISSUE TITLE
Nushell update 0.99 / automation

### ISSUE THREAD

**Issue by dougg0k** [tesujimath/nu_plugin_bash_env#32]
Hey,

Another update and there was no need to make any changes.

https://www.nushell.sh/blog/2024-10-15-nushell_0_99_0.html#notes-for-plugin-developers-toc

`Failed to send plugin call to bash_env`
`Plugin failed to load: Plugin bash_env is compiled for nushell version 0.98.0, which is not compatible with version 0.99.0`

I would suggest some automation like https://github.com/convictional/trigger-workflow-and-wait to automatically build a new version when there is a new release, I suppose with rust it would break if a breaking change were introduced, therefore it would require you to fix.

**Comment by tesujimath** [comment]
I'll get to this today or tomorrow. 

Cargo.toml has version numbers in it, which means automated version bumping is not straightforward. Or did you have a cunning idea?

**Comment by dougg0k** [comment]
Dont you have a whole bash environment under gh actions if used with linux? You can just overwrite the number and make it push the changes to the repo. 

If you google, there are probably helpers/actions to help do that.

**Comment by tesujimath** [comment]
Yeah but I think it's not worth the effort TBH.  Everything takes time, and that's not what I want to spend my time on.

I'm also interested in any answer which may be forthcoming to [this question](https://github.com/nushell/nushell/issues/14107).

**Comment by dougg0k** [comment]
In case it doesnt go through

- Triggers the new release flow
  - https://github.com/convictional/trigger-workflow-and-wait
- Get latest nushell version using curl + jq, and sed into Cargo.toml
- Get your current version, do a increase and or concat from nushell version depending how you want to set, major.minor.patch
- Push changes to repo
  - https://github.com/actions-js/push
- https://github.com/MarcoIeni/release-plz
  - This will
    - check cargo.toml version
    - cargo build
    - send to crates.io
    - create a new github release
- Done
