### ISSUE TITLE
Remains broken as the update were not uploaded to cargo.io

### ISSUE THREAD

**Issue by dougg0k** [tesujimath/nu_plugin_bash_env#43]
Title

**Comment by tesujimath** [comment]
Published `0.17.3`

Recommending you switch from the plugin to the module.  See the README for details.  The plugin is deprecated, and will soon become unmaintained.

**Comment by dougg0k** [comment]
How do you mean installed as executable, where did you generated the bash json executable?

Maybe provide some additional steps or straight scripts to be more automated and clear about it?

**Comment by tesujimath** [comment]
The `bash-env-json` script lives in its own repo. See the README there, which is linked from the README in this repo.

https://github.com/tesujimath/bash-env-json

Up to you how you install that script. I highly recommend Nix, which makes it easy. I don't think pure Nu can help there, but that is the subject of [another issue](https://github.com/tesujimath/bash-env-nushell/issues/41).

**Comment by dougg0k** [comment]
Rather than having to set as executable, I just had both files at the same folder. 

And modified https://github.com/tesujimath/bash-env-nushell/blob/main/bash-env.nu#L19 to `... | bash $"($env.FILE_PWD)/bash-env-json" ....`

**Comment by tesujimath** [comment]
Well, that's not a great solution in general, but if it works for you then be happy! 😁

**Comment by dougg0k** [comment]
It's not. 

But a more likely way for this to be automated would be to download the `bash-env-json` using curl or whatever in the `bash-env.nu` and put in it's side, if not available. With bash executing it. User would not need to do anything other than download the nu script and import into `config.nu`

Actually the $env.FILE_PWD seems to not work when loading from the import into config.nu. So I changed it, as I have put it into the scripts folder inside nushell config.

```
let bash_env_json_filepath = $"($nu.config-path | path dirname | path join 'scripts')/bash-env-json"
if (not ($bash_env_json_filepath | path exists)) {
    curl https://raw.githubusercontent.com/tesujimath/bash-env-json/refs/heads/main/bash-env-json --output $bash_env_json_filepath
}
let raw = ($in | str join "\n") | bash $bash_env_json_filepath ...($fn_args ++ $path_args) | complete
```

**Comment by dougg0k** [comment]
Another issue appeared.

If I run `ssh-agent | bash-env | load-env` straight into nushell, it seem to work. Even though there are no final output with load-env, there is with bash-env without load-env.

But if I run the command through a nushell script. 

```
Error: nu::shell::external_command

  × External command failed
    ╭─[/path/script.nu:29:13]
 28 │
 29 │ ssh-agent | bash-env | load-env
    ·             ────┬───
    ·                 ╰── Command `bash-env` not found
    ╰────
  help: `bash-env` is neither a Nushell built-in or a known external command
```

**Comment by tesujimath** [comment]
You're missing a `use` in your script. The module is not available globally, you have to use it where you need it.

**Comment by tesujimath** [comment]
Btw I won't be working on an ad hoc installation for Nu, because I install everything with Nix, which is so far superior to language specific approaches. Highly recommended.

**Comment by dougg0k** [comment]
Right. I didnt consider as I didnt wanted to deal with the very different path in the dotfiles. 

But this have worked. `use $"($nu.default-config-dir)/scripts/bash-env.nu"`

---

Ok. I took a look at nix, seems very config heavy as you seem to have control in most part of building it. Though I wont be using it for now.
