### ISSUE TITLE
Support for 0.92.1

### ISSUE THREAD

**Issue by Abdillah** [tesujimath/nu_plugin_bash_env#9]
The Plugin API change for Nu 0.92.1 is not well anticipated (thus pretty rough). Now, a record look like this.

```json
{
    "CallResponse": [
        0,
        {
            "PipelineData": {
                "Value": {
                    "Record": {
                        "val": {
                            "inner": [
                                [ "LESSHISTFILE", {
                                    "String": {
                                        "val": "/home/user/.local/share/less/lesshst",
                                        "span": {
                                            "start": 0,
                                            "end": 0
                                        }
                                    }
                                } ]
                            ]
                        },
                        "span": {
                            "start": 0,
                            "end": 0
                        }
                    }
                }
            }
        }
    ]
}
```

In the future, `Record` will have nice de-serialization structure like JSON object, but in this release it needs to be refactored.

I have read some of @tesujimath discussion on the Nushell, and wondering do you have in progress PR for 0.92 support? If not, I might be able to help.

Or do you plan to wait until next version?

**Comment by tesujimath** [comment]
Oh, it broke again! 😭 

I can fix this, was quite recently that I looked into it all for 0.92.0, shouldn't take long.  I'll sort it out as soon as I get a chance.

Thanks for reporting!

(Hope you're OK with 0.92.0 until I fix it up for 0.92.1)

**Comment by Abdillah** [comment]
Actually, I have a version of this plugin that accommodate the change.

Thank you!

**Comment by tesujimath** [comment]
Please make a PR then if you like 😊

**Comment by tesujimath** [comment]
@Abdillah In my testing with plugin version 0.7.1 against both nushell 0.92.1 and 0.92.2 it works fine.

Closing this as no problem that I can see.

**Comment by Abdillah** [comment]
Ah okay, thanks.
